export const ARTICLE_LIST_REQUEST = "ARTICLE_LIST_REQUEST";
export const ARTICLE_LIST_RECEIVE = "ARTICLE_LIST_RECEIVE";
export const ARTICLE_LIST_ERROR = "ARTICLE_LIST_ERROR";
export const ARTICLE_LIST_FETCH = "ARTICLE_LIST_FETCH";
export const ARTICLE_LIST_ADD = "ARTICLE_LIST_ADD";


export const ARTICLE_REQUEST = "ARTICLE_REQUEST";
export const ARTICLE_RECEIVED = "ARTICLE_RECEIVED";
export const ARTICLE_ERROR = "ARTICLE_ERROR";
export const ARTICLE_FETCH = "ARTICLE_FETCH";
export const ARTICLE_ADD = "ARTICLE_ADD";
export const ARTICLE_UNLOAD = "ARTICLE_UNLOAD";
export const ARTICLE_LIST_SET_PAGE = "ARTICLE_LIST_SET_PAGE";

export const COMMENT_LIST_REQUEST = "COMMENT_LIST_REQUEST";
export const COMMENT_LIST_RECEIVED = "COMMENT_LIST_RECEIVED";
export const COMMENT_LIST_ERROR = "COMMENT_LIST_ERROR";
export const COMMENT_LIST_UNLOAD = "COMMENT_LIST_UNLOAD";
export const COMMENT_LIST_ADD = "COMMENT_LIST_ADD";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";


export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_RECEIVED = "USER_PROFILE_RECEIVED";
export const USER_PROFILE_ERROR = "USER_PROFILE_ERROR";
export const USER_PROFILE_UNLOAD = "USER_PROFILE_UNLOAD";
export const USER_PROFILE_ADD = "USER_PROFILE_ADD";

export const USER_SET_ID = "USER_SET_ID";
export const COMMENT_ADDED = "COMMENT_ADDED";
export const COMMENT_ERROR = "COMMENT_ERROR";

export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_CONFIRMATION_SUCCESS = "USER_CONFIRMATION_SUCCESS";
export const USER_REGISTER_COMPLETED = "USER_REGISTER_COMPLETED";
export const ARTICLE_CREATED_SUCCESS = "ARTICLE_CREATED_SUCCESS";

export const IMAGE_UPLOADED = "IMAGE_UPLOADED";
export const IMAGE_UPLOAD_REQUEST = "IMAGE_UPLOAD_REQUEST";
export const IMAGE_UPLOAD_ERROR = "IMAGE_UPLOAD_ERROR";
export const ARTICLE_FORM_UNLOAD = "ARTICLE_FORM_UNLOAD";

export const IMAGE_DELETED = "IMAGE_DELETED";
